name: zkmf2024_app
description: "ZKMF2024 App"
publish_to: 'none'
version: 1.1.0+27

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.1
  go_router: ^14.1.4
  geolocator: ^12.0.0
  google_fonts: ^6.2.1
  get_storage: ^2.1.1
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.3.0
  cached_network_image: ^3.3.1
  flutter_markdown: ^0.7.1
  package_info_plus: ^8.0.0
  firebase_analytics: ^11.0.0
  firebase_core: ^3.0.0
  firebase_crashlytics: ^4.0.0
  firebase_messaging: ^15.0.0
  responsive_grid: ^2.4.4
  photo_view: ^0.15.0
  flutter_inappwebview: ^6.0.0
  permission_handler: ^11.3.1
  intl: ^0.19.0
  map_launcher: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo-home.png
    - assets/hauptsponsoren.png
    - assets/logo-mp.png
# TODO https://flutter.dev/assets-and-images/#resolution-aware
